spring:
  application:
    name: Multimedia_File_Security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multimedia_file_security?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto

# MinIO核心配置（自定义命名空间，方便通过@ConfigurationProperties注入）
minio:
  url: http://127.0.0.1:9005
  username: root
  password: 12345678
  bucketName: img